### ISSUE TITLE
JSON syntax highlighting off

### ISSUE THREAD

**Issue by martinbean** [nathanbuchar/atom-peacocks-in-space-syntax#2]
The syntax highlighting of JSON documents is off with this theme. For example, in the screen-shot below, object keys have different colours depending on the level they’re at (i.e. first or second).

![screen shot 2015-09-20 at 01 02 54](https://cloud.githubusercontent.com/assets/167312/9978629/c6464c50-5f33-11e5-8b22-c338ccb59566.png)

**Comment by nathanbuchar** [comment]
Thanks for flagging; I'll take care of this on Monday :-)

**Comment by nathanbuchar** [comment]
@martinbean I just checked the original Peacocks and Space theme for Sublime, and it too follows this pattern (see below). I'd like to stay as consistent with the Sublime theme as possible, so for now I will leave as is. If you notice anything else that you think might be wrong, feel free to call them out!

Edit: I'll see if there's something I can do about the quote coloring though. Might be a limitation of Atom, however.

Update: Fixed via 1a376cf

![d8kcef05x4cgqkavrh36omcfel5ww0qdoaelly6nk1e](https://cloud.githubusercontent.com/assets/1815367/9999925/e996b06c-604d-11e5-9f2f-46c4b3b952ed.png)

**Comment by martinbean** [comment]
@nathanbuchar Do you not think that’s a bug in the Sublime theme as well, though?

**Comment by nathanbuchar** [comment]
You're right, it could be; But it just as well could have been deliberate. The Peacocks in Space theme has been around for over two years, so if it were a bug—and an obvious one at that—I'm certain it would have been addressed by now. If you'd like you can open a ticket on [Dayle Rees' repo](https://github.com/daylerees/colour-schemes) which has the original Peacocks in Space theme and ask about it :-)

Alternatively you can fork my repository and change the keys on your own. All you'd need to change are lines [193](https://github.com/nathanbuchar/atom-peacocks-in-space-syntax/blob/master/styles/base.less#L193) and [196](https://github.com/nathanbuchar/atom-peacocks-in-space-syntax/blob/master/styles/base.less#L196) of `styles/base.less` from `@red` to `@green`.

Follow [these instructions](https://atom.io/docs/v1.0.15/hacking-atom-creating-a-theme#creating-an-interface-theme) for more information on how to create your own theme from an existing theme, and how to symlink it to your local `~/.atom/packages` directory.

Let me know if you have any other questions!
